repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
      - id: commitizen
        name: commitizen check
        entry: cz check --commit-msg-file $GIT_PARAMS
        language: python
        stages: [commit-msg]
