# Generated by Django 5.2.1 on 2025-07-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='complement',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
