# Generated by Django 5.2.1 on 2025-05-21 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='category',
            field=models.ManyToManyField(related_name='establishments_category', to='accounts.category'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishment_location', to='accounts.location'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='whatsapp',
            field=models.BigIntegerField(),
        ),
    ]
