# Generated by Django 5.2.1 on 2025-08-07 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_socialmedia_rename_cnpj_establishment_cnpj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='photos',
        ),
    ]
