# Generated by Django 5.2.1 on 2025-09-08 11:49

import accounts.models
from django.db import migrations, models
from accounts.utils import IDGenerator


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_establishment_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=lambda: IDGenerator.custom_id("U"), editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
