# Generated by Django 5.2.1 on 2025-09-08 11:56

from django.db import migrations, models
from accounts.utils import IDGenerator

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='id',
            field=models.CharField(default=lambda: IDGenerator.custom_id("E"), editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=lambda: IDGenerator.custom_id("E"), editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
