# Generated by Django 5.2.1 on 2025-10-25 13:17

import accounts.models.establishment
import accounts.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_establishment_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='id',
            field=models.CharField(default=accounts.models.establishment.generate_establishment_id, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='pix_key',
            field=models.CharField(blank=True, help_text='Chave Pix (e-mail, telefone, CPF/CNPJ ou aleatória)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='facebook',
            field=models.CharField(blank=True, help_text='Usuário do Facebook ex: joao_silva', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='instagram',
            field=models.CharField(blank=True, help_text='Usuário do Instagram ex: @joao_silva', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=accounts.models.user.generate_user_id, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('establishment', 'Establishment'), ('manager', 'Manager'), ('admin', 'Admin')], max_length=20),
        ),
    ]
