# Generated by Django 5.2.1 on 2025-08-07 22:29

import django.db.models.deletion
import photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_establishment_photos'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=photos.models.upload_to_path)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto alternativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('type_photo', models.CharField(choices=[('profile', 'Foto de Perfil'), ('gallery', 'Galeria'), ('product', 'Produto')], max_length=20, verbose_name='Tipo da foto')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='accounts.establishment', verbose_name='Estabelecimento')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
        migrations.DeleteModel(
            name='EstablishmentProfileImage',
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['establishment', 'type_photo'], name='photos_phot_establi_c66375_idx'),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.UniqueConstraint(condition=models.Q(('type_photo', 'profile')), fields=('establishment',), name='unique_profile_photo_per_establishment'),
        ),
    ]
